'use client';

import SharedContext from './shared-context';
import AgentIcon from './agent-icon';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowRight, Check, ChevronRight, Focus, Grip, FileText, List, Minus, MousePointer2, Plus, Pause, Play, RotateCcw, Search, X } from 'lucide-react';

type Point = { x: number; y: number };
type Member = { id: string; name: string; color: string; focus: string; initial: Point };
type AgentNode = { id: string; person: string; name: string; kind: string; task: string; description: string; next: string; status: 'Working' | 'Waiting' | 'Done'; time: string; initial: Point };
const members: Member[] = [
 { id: 'nathan', name: 'Nathan', color: 'lilac', focus: 'Making the product feel right', initial: { x: 275, y: 275 } },
 { id: 'khang', name: 'Khang', color: 'mint', focus: 'Getting everything connected', initial: { x: 870, y: 260 } },
 { id: 'gabriel', name: 'Gabriel', color: 'peach', focus: 'Finding the story', initial: { x: 590, y: 580 } },
];
const agents: AgentNode[] = [
 { id:'n-chat', person:'nathan', name:'ChatGPT', kind:'chatgpt', task:'Connecting the login flow', description:'The login UI is ready. Waiting for Khang’s authentication endpoint before connecting it.', next:'Read the API contract and connect the form.', status:'Waiting', time:'1 min ago', initial:{x:525,y:165} },
 { id:'n-code', person:'nathan', name:'Codex', kind:'codex', task:'Polishing the little details', description:'Shared buttons, inputs, and validation states are finished.', next:'Help with frontend integration.', status:'Done', time:'8 min ago', initial:{x:145,y:465} },
 { id:'k-chat', person:'khang', name:'ChatGPT', kind:'chatgpt', task:'Building the auth endpoint', description:'Login and session endpoints are implemented. Finishing the response contract for Nathan.', next:'Publish the API contract.', status:'Working', time:'2 min ago', initial:{x:1045,y:430} },
 { id:'k-code', person:'khang', name:'Codex', kind:'codex', task:'Checking the deployment', description:'Checking environment configuration and the production build.', next:'Share the deployment check results.', status:'Working', time:'3 min ago', initial:{x:1070,y:110} },
 { id:'g-claude', person:'gabriel', name:'Claude', kind:'claude', task:'Writing the demo story', description:'Turning the dependency handoff into a three-minute walkthrough.', next:'Capture the completed handoff.', status:'Working', time:'4 min ago', initial:{x:815,y:660} },
];
const initialPositions = Object.fromEntries([...members, ...agents].map(n => [n.id, n.initial]));
function Portrait({ person }: { person: string }) {
 const khang = person === 'khang', gabriel = person === 'gabriel';
 return <svg viewBox="0 0 100 100" aria-hidden="true"><defs><clipPath id={`clip-${person}`}><circle cx="50" cy="50" r="48"/></clipPath></defs><g clipPath={`url(#clip-${person})`}><circle cx="50" cy="50" r="50" fill={khang?'#caf0dc':gabriel?'#ffdcc4':'#e2d7fb'}/><path d="M15 106Q14 72 50 72Q86 72 87 106" fill={khang?'#385e50':gabriel?'#da724c':'#8270c6'}/><path d="M40 66h20v17q-10 9-20 0" fill="#d69a75"/><ellipse cx="50" cy="47" rx="24" ry="29" fill={gabriel?'#d79973':'#efbc94'}/><path d={gabriel?'M25 45Q15 20 35 17Q44 5 60 15Q85 9 79 44L69 30Q52 39 31 29Z':khang?'M25 47Q14 15 47 14Q82 8 78 44L66 29Q48 40 28 32Z':'M24 44Q18 9 52 12Q82 12 77 43L70 27Q53 37 27 30Z'} fill={gabriel?'#573e34':'#333537'}/><path d="M44 61q6 5 12 0" fill="none" stroke="#9b6050" strokeWidth="2" strokeLinecap="round"/><path d="M50 45l-2 9h4" fill="none" stroke="#ce9677" strokeWidth="1.5"/><circle cx="39" cy="45" r="2" fill="#333537"/><circle cx="62" cy="45" r="2" fill="#333537"/>{!gabriel&&<g fill="none" stroke="#414246" strokeWidth="2"><rect x="29" y="38" width="18" height="14" rx="5"/><rect x="54" y="38" width="18" height="14" rx="5"/><path d="M47 43h7M24 41h5M72 41h5"/></g>}{gabriel&&<path d="M31 59Q33 79 50 79Q68 76 70 57L63 64Q50 73 38 62Z" fill="#573e34" opacity=".8"/>}</g></svg>;
}
export default function Home(){
 const [motion,setMotion]=useState(true);
 const [page,setPage]=useState<'canvas'|'log'|'context'>('canvas'); const [tab,setTab]=useState('All'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string|null>(null);
 const [positions,setPositions]=useState<Record<string,Point>>(initialPositions); const [camera,setCamera]=useState({x:0,y:0,scale:1}); const [dragging,setDragging]=useState(false);
 const surface=useRef<HTMLDivElement>(null); const gesture=useRef<{id:string|null;start:Point;origin:Point;scale:number}|null>(null); const moved=useRef(false);
 const fit=useCallback(()=>{ const el=surface.current;if(!el)return;const scale=Math.min(1.12,(el.clientWidth-60)/1250,(el.clientHeight-140)/800);setCamera({x:(el.clientWidth-1250*scale)/2,y:(el.clientHeight-800*scale)/2,scale:Math.max(.2,scale)}); },[]);
 useEffect(()=>{if(page!=='canvas')return;const el=surface.current;if(!el)return;const initialView=()=>{if(el.clientWidth<600)setCamera({x:el.clientWidth/2-370*.7,y:el.clientHeight/2-320*.7,scale:.7});else fit();};initialView();const observer=new ResizeObserver(initialView);observer.observe(el);return()=>observer.disconnect();},[fit,page]);
 useEffect(()=>{const el=surface.current;if(!el||page!=='canvas')return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect();setCamera(c=>{if(e.ctrlKey||e.metaKey){const scale=Math.max(.2,Math.min(2,c.scale*Math.exp(-e.deltaY*.008)));const px=e.clientX-r.left,py=e.clientY-r.top;return{x:px-(px-c.x)*scale/c.scale,y:py-(py-c.y)*scale/c.scale,scale};}return{...c,x:c.x-e.deltaX,y:c.y-e.deltaY};});};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[page]);
 const zoom=(amount:number)=>{const el=surface.current;if(!el)return;setCamera(c=>{const scale=Math.max(.2,Math.min(2,c.scale+amount));return{x:el.clientWidth/2-(el.clientWidth/2-c.x)*scale/c.scale,y:el.clientHeight/2-(el.clientHeight/2-c.y)*scale/c.scale,scale};});};
 const begin=(e:React.PointerEvent,id:string|null)=>{if(e.button!==0)return;e.stopPropagation();moved.current=false;gesture.current={id,start:{x:e.clientX,y:e.clientY},origin:id?positions[id]:{x:camera.x,y:camera.y},scale:camera.scale};e.currentTarget.setPointerCapture(e.pointerId);setDragging(true);};
 const move=(e:React.PointerEvent)=>{const g=gesture.current;if(!g)return;const dx=e.clientX-g.start.x,dy=e.clientY-g.start.y;if(Math.abs(dx)+Math.abs(dy)>4)moved.current=true;if(g.id)setPositions(p=>({...p,[g.id!]:{x:g.origin.x+dx/g.scale,y:g.origin.y+dy/g.scale}}));else setCamera(c=>({...c,x:g.origin.x+dx,y:g.origin.y+dy}));};
 const end=()=>{gesture.current=null;setDragging(false);};
 const current=agents.find(a=>a.id===selected); const human=members.find(p=>p.id===selected); const owner=members.find(p=>p.id===current?.person);
 const filtered=agents.filter(a=>(tab==='All'||(tab==='Now'?a.status!=='Done':a.status==='Done'))&&`${a.task} ${a.name} ${a.person}`.toLowerCase().includes(query.toLowerCase()));
 const nodeProps=(id:string)=>({onPointerDown:(e:React.PointerEvent)=>begin(e,id),onPointerMove:move,onPointerUp:end,onPointerCancel:end,onClick:()=>{if(!moved.current)setSelected(id);}});
 return <div className={`app ${motion?'':'motion-paused'}`}>
  <header className="floating-header"><a href="/" className="brand"><span className="loop-logo">a<span>↗</span></span><span>agent in the loop<span className="brand-period">.</span></span></a><nav className="view-switch" aria-label="Workspace view"><button className={page==='canvas'?'chosen':''} onClick={()=>{setPage('canvas');setSelected(null);}}><Grip size={16}/>Canvas</button><button className={page==='log'?'chosen':''} onClick={()=>{setPage('log');setSelected(null);}}><List size={16}/>Log<span className="nav-badge">5</span></button><button className={page==='context'?'chosen':''} onClick={()=>{setPage('context');setSelected(null);}}><FileText size={16}/>Share Context</button></nav><div className="room"><span className="room-dot"/>The build room<span className="room-avatars"><span>👨🏻‍💻</span><span>🧑🏻‍🚀</span><span>🧔🏽</span></span></div></header>
  {page==='canvas'?<>
   <div className="canvas-intro"><span className="eyebrow">A little space for the whole team</span><h1>Who’s doing what?</h1><p>3 humans. 5 agents. One shared picture.</p></div>
   <div ref={surface} className={`canvas ${dragging?'dragging':''}`} aria-label="Team canvas. Drag to pan. Use zoom buttons or Control plus scroll to zoom." tabIndex={0} onPointerDown={e=>begin(e,null)} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);if(e.target!==e.currentTarget)return;const shifts:Record<string,Point>={ArrowLeft:{x:50,y:0},ArrowRight:{x:-50,y:0},ArrowUp:{x:0,y:50},ArrowDown:{x:0,y:-50}};if(shifts[e.key]){e.preventDefault();setCamera(c=>({...c,x:c.x+shifts[e.key].x,y:c.y+shifts[e.key].y}));}if(e.key==='+'||e.key==='=')zoom(.1);if(e.key==='-')zoom(-.1);}} style={{backgroundPosition:`${camera.x}px ${camera.y}px`,backgroundSize:`${24*camera.scale}px ${24*camera.scale}px`}}>
    <div className="canvas-world" style={{transform:`translate(${camera.x}px,${camera.y}px) scale(${camera.scale})`}}>
     <svg className="connections" width="1250" height="800" aria-hidden="true" style={{overflow:'visible'}}>{agents.map((a,i)=>{const p=positions[a.person],q=positions[a.id];const path=`M ${p.x} ${p.y} C ${p.x+(q.x-p.x)*.65} ${p.y}, ${q.x-(q.x-p.x)*.65} ${q.y}, ${q.x} ${q.y}`;return <g key={a.id}><path className={`thread ${a.person}`} d={path}/>{a.status==='Working'&&<><path className={`signal signal-halo ${a.person}`} d={path} pathLength={100} style={{animationDelay:`${-i*1.4}s`}}/><path className={`signal ${a.person}`} d={path} pathLength={100} style={{animationDelay:`${-i*1.4}s`}}/></>}</g>;})}<path className="dependency-thread" d={`M${positions['n-chat'].x+100} ${positions['n-chat'].y+45} Q${positions['k-chat'].x-80} ${positions['n-chat'].y+90} ${positions['k-chat'].x-40} ${positions['k-chat'].y-15}`}/></svg>
     <div className="canvas-note" style={{left:650,top:330}}><ArrowDownLeft size={24}/><span>these two are<br/>figuring out auth</span></div>
     {members.map((p,i)=><button key={p.id} {...nodeProps(p.id)} className={`human-node ${p.color} ${selected===p.id?'selected':''}`} style={{left:positions[p.id].x,top:positions[p.id].y,animationDelay:`${i*100}ms`}} aria-label={`${p.name}: ${p.focus}. Drag to move or click for details.`}><span className="human-bubble">{p.focus}</span><span className="portrait"><Portrait person={p.id}/></span><strong>{p.name}{p.id==='nathan'&&<span className="you-label">you</span>}</strong><span className="human-sub">{agents.filter(a=>a.person===p.id).length} {agents.filter(a=>a.person===p.id).length===1?'agent':'agents'} in their loop</span></button>)}
     {agents.map((a,i)=><button key={a.id} {...nodeProps(a.id)} className={`agent-node state-${a.status.toLowerCase()} ${a.person} ${selected===a.id?'selected':''}`} style={{left:positions[a.id].x,top:positions[a.id].y,animationDelay:`${250+i*85}ms`}} aria-label={`${members.find(p=>p.id===a.person)?.name}'s ${a.name}: ${a.task}. ${a.status}`}><span className={`agent-orb ${a.kind}`}><AgentIcon kind={a.kind}/><span className={`state-dot ${a.status.toLowerCase()}`}>{a.status==='Done'&&<Check size={9}/>}</span></span><span className="agent-caption"><span className="agent-name">{a.name}<span>{a.status==='Working'?'working':a.status.toLowerCase()}</span></span><strong>{a.task}</strong><span className="agent-meta">{a.status==='Waiting'?'↳ needs Khang’s API':a.time}</span></span></button>)}
    </div>
   </div>
   <div className="canvas-bottom"><div className="canvas-hint"><MousePointer2 size={14}/><span>Move people around. Follow the threads.</span></div><div className="canvas-tools"><button aria-label={motion?'Pause canvas animations':'Play canvas animations'} aria-pressed={!motion} title={motion?'Pause motion':'Play motion'} onClick={()=>setMotion(!motion)}>{motion?<Pause size={14}/>:<Play size={14}/>}</button><i/><button aria-label="Zoom out" onClick={()=>zoom(-.1)}><Minus size={16}/></button><span>{Math.round(camera.scale*100)}%</span><button aria-label="Zoom in" onClick={()=>zoom(.1)}><Plus size={16}/></button><i/><button aria-label="Fit everyone on screen" title="Fit everyone" onClick={fit}><Focus size={17}/></button><button aria-label="Reset positions" title="Reset positions" onClick={()=>{setPositions(initialPositions);fit();}}><RotateCcw size={15}/></button></div><span className="sample-label"><span/>Sample world · not live</span></div>
  </>:page==='context'?null:<main className="log-page"><div className="log-heading"><span className="eyebrow">The shared memory</span><h1>A little less “any updates?”</h1><p>What’s happening now, and what’s already in the bag.</p></div><div className="log-toolbar"><div className="log-tabs">{['All','Now','Done'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}<span>{t==='All'?5:t==='Now'?4:1}</span></button>)}</div><label className="search"><Search size={16}/><input aria-label="Search log" placeholder="Find a person, agent, or task" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="log-date">Today <span>September 12 · Sample activity</span></div><section className="log-list" aria-label="Activity log">{filtered.map(a=>{const p=members.find(p=>p.id===a.person)!;return <button className="log-row" key={a.id} onClick={()=>setSelected(a.id)}><span className={`log-avatar ${p.color}`}><Portrait person={p.id}/><span className={`log-agent ${a.kind}`}><AgentIcon kind={a.kind}/></span></span><span className="log-body"><span className="log-byline">{p.name}<span>/</span>{a.name}</span><strong>{a.task}</strong><span>{a.description}</span></span><span className={`log-status ${a.status.toLowerCase()}`}>{a.status==='Done'?<Check size={12}/>:<span/>}{a.status==='Working'?'In progress':a.status}</span><span className="log-time">{a.time}</span><ChevronRight size={17}/></button>;})}{filtered.length===0&&<div className="empty"><Search size={25}/><h2>Nothing here just yet.</h2><p>Try a different name or switch the filter.</p><button onClick={()=>{setQuery('');setTab('All');}}>Show all activity</button></div>}</section><div className="log-end">You’re in the loop.<span>All activity shown here is sample data.</span></div></main>}
  <div hidden={page!=='context'}><SharedContext/></div>
  {selected&&<aside className="peek" role="dialog" aria-label={current?`${owner?.name}'s ${current.name}`:human?.name} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><button className="close" aria-label="Close details" onClick={()=>setSelected(null)}><X size={18}/></button>{current?<><span className={`peek-orb agent-orb ${current.kind}`}><AgentIcon kind={current.kind}/></span><span className="eyebrow">In {owner?.name}’s loop</span><h2>{current.name}</h2><span className={`log-status ${current.status.toLowerCase()}`}>{current.status}</span><h3>{current.task}</h3><p>{current.description}</p><div className="next"><span>Up next</span><p>{current.next}</p></div><small>Last reported {current.time} · Sample activity</small><button className="peek-link" onClick={()=>{setPage('log');setQuery(current.person);setSelected(null);}}>See {owner?.name}’s log <ArrowRight size={14}/></button></>:human?<><span className="peek-portrait"><Portrait person={human.id}/></span><span className="eyebrow">Human in the loop</span><h2>{human.name}</h2><p>{human.focus}</p><small>Sample self-reported focus</small><div className="human-agent-list">{agents.filter(a=>a.person===human.id).map(a=><button key={a.id} onClick={()=>setSelected(a.id)}><AgentIcon kind={a.kind}/><span>{a.name}<small>{a.task}</small></span><ChevronRight size={16}/></button>)}</div></>:null}</aside>}
 </div>;
}
