'use client';

import { useEffect, useState } from 'react';
import { Check, Copy, Download, FileText, Pencil, BookOpen } from 'lucide-react';

const startingDocs = {
  'Plan.md': `# The plan\n\nBuild a shared workspace for humans and their personal agents.\n\n## Our first milestone\n\nTwo agents exchange useful context and complete one dependency handoff.\n\n## What we’re building\n\n- A canvas showing humans, their agents, and current work.\n- A log of work in progress and completed tasks.\n- One shared plan and one shared context document.\n- A shared API where agents read context and post updates.\n\n## Who owns what\n\n- Nathan: agent instructions and frontend direction.\n- Backend owner: API, Neon database, and Vercel deployment.\n- Integration owner: connect two agents and rehearse the demo.\n\n## Build order\n\n1. Agree on the API contract and register agent identities.\n2. Connect two agents to the workspace.\n3. Record a blocker and complete its dependency.\n4. Have the blocked agent read context and resume.\n5. Show the handoff on the canvas and in the log.\n\n## Done means\n\nThe receiving agent uses the shared artifact without its human copying context between conversations.`,
  'Context.md': `# What everyone should know\n\nAgent in the loop is a shared workspace for a team of humans, each working with their own AI agents.\n\n## Why it exists\n\nSeparate agents mostly know what their own human is doing. Shared project context helps them avoid duplicated work, spot dependencies, and hand work over.\n\n## The team\n\n- Nathan works with ChatGPT and Codex.\n- Khang works with ChatGPT and Codex.\n- Gabriel works with Claude.\n\n## Decisions so far\n\n- Humans stay at the center of the canvas, with their agents connected around them.\n- The frontend shows reported activity, not inferred live presence.\n- Use Next.js on Vercel and Neon Postgres through Vercel Marketplace.\n- Give each agent connection its own credential; the server resolves its identity.\n- Store rich context, but retrieve compact project summaries.\n\n## How agents participate\n\nBefore meaningful work, read project state and check dependencies. After meaningful work, publish progress, blockers, artifacts, and the next intended step.\n\n## Current prototype\n\nThe canvas and log use sample data. These documents are local drafts; there is no shared backend or automatic agent access yet.\n\n## Keep out of the first build\n\nNo automatic agent wakeups, full transcript ingestion, complex permissions, or universal connector.`,
};
type DocName = keyof typeof startingDocs;
function ReadingView({text}:{text:string}) {
 return <div className="document-reading">{text.split('\n').map((line,i)=>line.startsWith('# ')?<h2 key={i}>{line.slice(2)}</h2>:line.startsWith('## ')?<h3 key={i}>{line.slice(3)}</h3>:line.startsWith('- ')?<p className="document-bullet" key={i}><span>•</span>{line.slice(2)}</p>:line?<p key={i}>{line}</p>:<div className="document-space" key={i}/>)}</div>;
}
export default function SharedContext(){
 const [docs,setDocs]=useState(startingDocs);const [saved,setSaved]=useState(startingDocs);const [active,setActive]=useState<DocName>('Plan.md');const [editing,setEditing]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{try {const stored=localStorage.getItem('agent-in-loop-shared-docs-v1');if(stored){const value=JSON.parse(stored);if(typeof value['Plan.md']==='string'&&typeof value['Context.md']==='string'){setDocs(value);setSaved(value);}}}catch{setNotice('Local storage is unavailable. You can still edit and download your draft.');}},[]);
 const dirty=docs[active]!==saved[active];
 function save(){try{localStorage.setItem('agent-in-loop-shared-docs-v1',JSON.stringify(docs));setSaved({...docs});setNotice('Saved in this browser. Team sync is not connected yet.');}catch{setNotice('Could not save in this browser. Download your draft to keep it.');}}
 async function copy(){try{await navigator.clipboard.writeText(docs[active]);setNotice(`${active} copied.`);}catch{setNotice('Clipboard unavailable. Switch to Edit to select and copy the text.');}}
 function download(){const url=URL.createObjectURL(new Blob([docs[active]],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=active;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${active} downloaded.`);}
 return <main className="context-page"><div className="log-heading"><span className="eyebrow">The same starting point</span><h1>A plan. A little shared context.</h1><p>Two documents to keep every human and agent on the same page.</p></div><div className="context-layout"><aside className="document-list" aria-label="Shared documents">{(Object.keys(startingDocs) as DocName[]).map(name=><button key={name} className={active===name?'active':''} aria-pressed={active===name} onClick={()=>{setActive(name);setNotice('');}}><span className={`document-icon ${name==='Plan.md'?'plan-icon':'context-icon'}`}><FileText size={20}/></span><span><strong>{name}{docs[name]!==saved[name]&&<span className="draft-dot" aria-label="Unsaved changes"/>}</strong><small>{name==='Plan.md'?'Where we’re going':'What we all know'}</small></span></button>)}<div className="context-note"><span>One of each. For everyone.</span><p>The plan holds the next steps.<br/>The context holds the why.</p></div></aside><section className="document-panel" aria-label={active}><header className="document-toolbar"><div className="document-title"><FileText size={15}/><strong>{active}</strong><span>{dirty?'Unsaved draft':'Local draft'}</span></div><div className="document-actions"><button aria-label={`Copy ${active}`} onClick={copy}><Copy size={15}/></button><button aria-label={`Download ${active}`} onClick={download}><Download size={15}/></button><span className="document-action-divider"/><button className="edit-document" onClick={()=>setEditing(!editing)}>{editing?<BookOpen size={14}/>:<Pencil size={14}/>} {editing?'Read':'Edit'}</button></div></header>{editing?<textarea className="document-editor" aria-label={`Edit ${active}`} spellCheck={false} value={docs[active]} onChange={e=>setDocs({...docs,[active]:e.target.value})}/>:<ReadingView text={docs[active]}/>}<footer className="document-footer"><span>Browser-only preview · not shared with agents yet</span><button disabled={!dirty} onClick={save}><Check size={14}/>Save locally</button></footer></section></div><p className="context-notice" role="status">{notice||'Sample starting documents. Edit, copy, or download either Markdown file.'}</p></main>;
}
