import test from 'node:test';
import assert from 'node:assert/strict';
import {buildWorkspace,normalizeState,relativeTime} from '../lib/workspace-view.ts';
const task={project_id:'agent-colab',task_id:'test-task',update_id:'test-start',agent_id:'nathan-codex',person:'Nathan',task:'Connect live state',status:'in_progress',summary:'Working',blocker:null,depends_on:[],artifact:null,next:'Verify',sequence:'1',created_at:'2026-09-12T06:00:00Z'};
const state=(tasks,recent_updates=tasks)=>({project_id:'agent-colab',generated_at:'2026-09-12T06:00:00Z',tasks,recent_updates,insights:[]});
test('accepts legacy deployed timestamp and rejects malformed snapshots',()=>{assert.equal(normalizeState(state([task])).tasks[0].timestamp,task.created_at);assert.throws(()=>normalizeState(state([{...task,created_at:'bad'}])));assert.throws(()=>normalizeState({}));});
test('current state and history remain separate after completion',()=>{const done={...task,status:'done',update_id:'test-done',sequence:'2',created_at:'2026-09-12T06:01:00Z'};const view=buildWorkspace(normalizeState(state([done],[done,task])));assert.equal(view.agents.length,0);assert.equal(view.canvasAgents.length,0);assert.deepEqual(view.activity.map(a=>a.status),['Done','Working']);assert.equal(view.members[0].focus,'0 open tasks');assert.equal(view.activity[0].kind,'codex');});
test('new people, generic identities, dependencies and artifact links survive mapping',()=>{const input={...task,person:'New teammate',agent_id:'unspecified-agent',depends_on:['other-task'],artifact:'https://example.com/output'};const view=buildWorkspace(normalizeState(state([input])));assert.equal(view.members[0].name,'New teammate');assert.equal(view.agents[0].kind,'unknown');assert.equal(view.agents[0].name,'unspecified-agent');assert.deepEqual(view.agents[0].dependsOn,['other-task']);assert.equal(view.agents[0].artifact,input.artifact);});
test('empty project is empty rather than populated with sample users',()=>{const view=buildWorkspace(normalizeState(state([])));assert.equal(view.members.length,0);assert.equal(view.agents.length,0);assert.equal(relativeTime('invalid'),'Time unavailable');});

test('one canvas node per human and agent, with every open task accessible',()=>{const other={...task,task_id:'second',update_id:'second-start',task:'Other work'};const view=buildWorkspace(normalizeState(state([task,other])));assert.equal(view.agents.length,2);assert.equal(view.canvasAgents.length,1);assert.equal(view.canvasAgents[0].openTasks.length,2);assert.equal(view.taskPositions.second,view.canvasAgents[0].id);});
